### ISSUE TITLE
The output window gets the focus every time a new output occurs.

### ISSUE THREAD

**Issue by tndev** [PluginCafe/Cinema4D_Connector-VisualStudioCode_Extension#2]
Whenever some new output is added to the console during the execution of python code, the "Output" tab and the "Cinema 4D" output are selected. In addition to that, this output window also receives focus.

Usually, this is not a problem, but if you have a long-running script that regularly writes output to the console and wants to continue working in VS Code simultaneously, then it becomes frustrating due to this behavior.

The problem seems to originate from this part of the code:

https://github.com/PluginCafe/Cinema4D_Connector-VisualStudioCode_Extension/blob/2b628fbc500b19841099378c5a01d1a112709db9/src/commands.ts#L65-L83

More precisely, this line:
https://github.com/PluginCafe/Cinema4D_Connector-VisualStudioCode_Extension/blob/2b628fbc500b19841099378c5a01d1a112709db9/src/commands.ts#L77

I assume the call of `.show()` will result in the output window being shown receiving the focus.

If that behavior is intended, it would be nice if there is a setting to disable that behavior.

**Comment by gr4ph0s** [comment]
Hi @tndev thanks a lot, this was indeed the intended behavior, as it may not be obvious that this feature exist and that you have other logger available or even that you receive new content to it. 

But I clearly understand the issue as well. 
For the moment I would say if you don't want to be pissed by that, the best way is to disconnect Vs Code with Cinema 4D when you don't use it. But introducing an option to allow or not this behavior is a good idea that I'm going to have a look when I do have time to work on this project.

Thanks a lot for your feedback!
Cheers,
Maxime.

**Comment by tndev** [comment]
> the best way is to disconnect Vs Code with Cinema 4D when you don't use it.

That's what I currently do. The issue is that I sometimes forget to disconnect, and I'm then confused when I lose focus in the window where I'm currently typing.

It would be fine for me if the output window shows itself as long as it does not take away the focus from where I am currently typing. So I guess setting `preserveFocus` to `true` for `show(preserveFocus?: boolean): void` would already be sufficient for me.

**Comment by gr4ph0s** [comment]
Will see what I can do within the upcoming days :)

**Comment by gr4ph0s** [comment]
Added an option in version 1.1.0 to choose the behavior
